root: true
extends:
  - 'plugin:vue/recommended'
  - 'airbnb-base'
env:
  browser: true
rules:
  no-bitwise: 0
  no-extra-semi: 2
  no-param-reassign: 0
  no-plusplus: 0
  no-return-assign: 0
  no-shadow: 0
  no-underscore-dangle: 0
  no-use-before-define: 0
  semi: 0
overrides:
  - files: ['*.vue']
    rules:
      indent: 'off'
      vue/no-parsing-error: [2, { "x-invalid-end-tag": false }]
